import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://chasecee.com"),
  title: "Cee App",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/studio/favicon.ico",
    shortcut: "/icons/studio/favicon-96x96.png",
    apple: "/icons/studio/apple-touch-icon.png",
  },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="m-0">{children}</body>
    </html>
  );
}
