import { getPages } from '@/sanity/sanity-utils';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const bodyClass = 'w-full min-h-screen bg-white dark:bg-neutral-900 text-neutral-900 dark:text-white font-normal';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={inter.className + bodyClass}>{children}</body>
    </html>
  )
}
