/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../site/schema.json
export type Ratio = {
  desktop?: string;
  mobile?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type MediaMedia = {
  asset?: SanityFileAssetReference;
  media?: unknown // Unable to locate the referenced type "media.media.media" in schema
;
  _type: "file";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Columns = {
  _type: "columns";
  columns?: Array<{
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      _key: string;
    } & Columns | {
      _key: string;
    } & Embed | {
      _key: string;
    } & Spotify | {
      _key: string;
    } & Gallery | {
      _key: string;
    } & Skills | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    } | {
      media?: MediaMedia;
      _type: "media";
      _key: string;
    }>;
    _type: "column";
    _key: string;
  }>;
  valign?: "top" | "center" | "bottom";
};

export type SiteMini = {
  _type: "siteMini";
  url?: string;
  embedUrl?: string;
  title?: string;
};

export type Spotify = {
  _type: "spotify";
  url?: string;
  size?: "default" | "compact";
  theme?: "dark" | "light";
  title?: string;
};

export type Embed = {
  _type: "embed";
  url?: string;
  title?: string;
  width?: "content" | "full";
  ratio?: Ratio;
  aspectRatio?: string;
};

export type Skills = {
  _type: "skills";
  placeholder?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type MusicReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "music";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  leadIn?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    } | {
      reference?: ProjectReference | PageReference | MusicReference;
      _type: "internalLink";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityFileAssetReference;
    media?: unknown;
    alt?: string;
    _type: "videoFile";
    _key: string;
  } | {
    _key: string;
  } & Columns | {
    _key: string;
  } & Embed | {
    _key: string;
  } & Spotify | {
    _key: string;
  } & Gallery | {
    _key: string;
  } & Skills | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | {
    media?: MediaMedia;
    _type: "media";
    _key: string;
  }>;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    } | {
      reference?: ProjectReference | PageReference | MusicReference;
      _type: "internalLink";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityFileAssetReference;
    media?: unknown;
    alt?: string;
    _type: "videoFile";
    _key: string;
  } | {
    _key: string;
  } & Columns | {
    _key: string;
  } & Embed | {
    _key: string;
  } & Spotify | {
    _key: string;
  } & Gallery | {
    _key: string;
  } & Skills | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | {
    media?: MediaMedia;
    _type: "media";
    _key: string;
  }>;
  type?: "personal" | "client";
  subtitle?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  svgcode?: Code;
  color?: Color;
  displayType?: "popup" | "background" | "embed";
  embedUrl?: string;
  aspectRatio?: {
    desktop?: string;
    mobile?: string;
  };
  url?: string;
  siteMini?: SiteMini;
  archived?: boolean;
  orderRank?: string;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Music = {
  _id: string;
  _type: "music";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  bandName?: string;
  albumName?: string;
  releaseYear?: number;
  slug?: Slug;
  albumArt?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Gallery;
  links?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  embeds?: Array<{
    _key: string;
  } & Embed | {
    _key: string;
  } & Spotify>;
  orderRank?: string;
};

export type Gallery = {
  _type: "gallery";
  columns?: 1 | 2 | 3 | 4 | 5 | 6 | 0;
  images?: Array<{
    _key: string;
  } & GalleryImage>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
  } & Columns | {
    _key: string;
  } & Embed | {
    _key: string;
  } & Spotify | {
    _key: string;
  } & Gallery | {
    _key: string;
  } & Skills | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | {
    media?: MediaMedia;
    _type: "media";
    _key: string;
  }>;
  title?: string;
  subtitle?: string;
  slug?: Slug;
  orderRank?: string;
};

export type GalleryImage = {
  _type: "galleryImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Ratio | SanityFileAssetReference | MediaMedia | SanityImageAssetReference | Columns | SiteMini | Spotify | Embed | Skills | ProjectReference | PageReference | MusicReference | Project | Color | Code | SanityImageCrop | SanityImageHotspot | Music | Gallery | Slug | Page | GalleryImage | RgbaColor | HsvaColor | HslaColor | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../site/sanity/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{  _id,  _type,  "isDraft": _id in path("drafts.**") || _originalId in path("drafts.**"),  _createdAt,  name,  "slug": slug.current,  "image": image.asset->url,  subtitle,  svgcode,  url,  archived,  siteMini,  orderRank,  "leadIn": leadIn[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      "slug": @.reference->slug.current,      "refType": @.reference->_type    },    _type == "link" => {      ...,    }  }},  "content": content[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      "slug": @.reference->slug.current,      "refType": @.reference->_type    },    _type == "link" => {      ...,    }  }}}
export type PROJECT_QUERY_RESULT = {
  _id: string;
  _type: "project";
  isDraft: boolean;
  _createdAt: string;
  name: string | null;
  slug: string | null;
  image: string | null;
  subtitle: string | null;
  svgcode: Code | null;
  url: string | null;
  archived: boolean | null;
  siteMini: SiteMini | null;
  orderRank: string | null;
  leadIn: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      reference?: MusicReference | PageReference | ProjectReference;
      _type: "internalLink";
      _key: string;
      slug: string | null;
      refType: "music" | "page" | "project" | null;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "columns";
    columns?: Array<{
      content?: Array<{
        _key: string;
      } & Columns | {
        _key: string;
      } & Embed | {
        _key: string;
      } & Gallery | {
        _key: string;
      } & Skills | {
        _key: string;
      } & Spotify | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      } | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      } | {
        media?: MediaMedia;
        _type: "media";
        _key: string;
      }>;
      _type: "column";
      _key: string;
    }>;
    valign?: "bottom" | "center" | "top";
    markDefs: null;
  } | {
    _key: string;
    _type: "embed";
    url?: string;
    title?: string;
    width?: "content" | "full";
    ratio?: Ratio;
    aspectRatio?: string;
    markDefs: null;
  } | {
    _key: string;
    _type: "gallery";
    columns?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
    images?: Array<{
      _key: string;
    } & GalleryImage>;
    markDefs: null;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
    markDefs: null;
  } | {
    media?: MediaMedia;
    _type: "media";
    _key: string;
    markDefs: null;
  } | {
    _key: string;
    _type: "skills";
    placeholder?: string;
    markDefs: null;
  } | {
    _key: string;
    _type: "spotify";
    url?: string;
    size?: "compact" | "default";
    theme?: "dark" | "light";
    title?: string;
    markDefs: null;
  } | {
    asset?: SanityFileAssetReference;
    media?: unknown;
    alt?: string;
    _type: "videoFile";
    _key: string;
    markDefs: null;
  }> | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      reference?: MusicReference | PageReference | ProjectReference;
      _type: "internalLink";
      _key: string;
      slug: string | null;
      refType: "music" | "page" | "project" | null;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "columns";
    columns?: Array<{
      content?: Array<{
        _key: string;
      } & Columns | {
        _key: string;
      } & Embed | {
        _key: string;
      } & Gallery | {
        _key: string;
      } & Skills | {
        _key: string;
      } & Spotify | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      } | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      } | {
        media?: MediaMedia;
        _type: "media";
        _key: string;
      }>;
      _type: "column";
      _key: string;
    }>;
    valign?: "bottom" | "center" | "top";
    markDefs: null;
  } | {
    _key: string;
    _type: "embed";
    url?: string;
    title?: string;
    width?: "content" | "full";
    ratio?: Ratio;
    aspectRatio?: string;
    markDefs: null;
  } | {
    _key: string;
    _type: "gallery";
    columns?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
    images?: Array<{
      _key: string;
    } & GalleryImage>;
    markDefs: null;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
    markDefs: null;
  } | {
    media?: MediaMedia;
    _type: "media";
    _key: string;
    markDefs: null;
  } | {
    _key: string;
    _type: "skills";
    placeholder?: string;
    markDefs: null;
  } | {
    _key: string;
    _type: "spotify";
    url?: string;
    size?: "compact" | "default";
    theme?: "dark" | "light";
    title?: string;
    markDefs: null;
  } | {
    asset?: SanityFileAssetReference;
    media?: unknown;
    alt?: string;
    _type: "videoFile";
    _key: string;
    markDefs: null;
  }> | null;
} | null;

// Source: ../site/sanity/queries.ts
// Variable: MUSIC_QUERY
// Query: *[_type == "music" && (slug.current == $slug || _id == $slug)][0]{  _id,  _type,  "isDraft": _id in path("drafts.**") || _originalId in path("drafts.**"),  _createdAt,  "slug": coalesce(slug.current, _id),  bandName,  albumName,  releaseYear,  "albumArt": albumArt.asset->url,  "albumArtAlt": albumArt.alt,  "gallery": {    "columns": coalesce(gallery.columns, 2),    "images": coalesce(gallery.images, gallery)[]{      _key,      asset,      "url": asset->url,      alt,      caption    }  },  links,  embeds}
export type MUSIC_QUERY_RESULT = {
  _id: string;
  _type: "music";
  isDraft: boolean;
  _createdAt: string;
  slug: string;
  bandName: string | null;
  albumName: string | null;
  releaseYear: number | null;
  albumArt: string | null;
  albumArtAlt: string | null;
  gallery: {
    columns: 0 | 1 | 2 | 3 | 4 | 5 | 6;
    images: Array<{
      _key: string;
      asset: SanityImageAssetReference | null;
      url: string | null;
      alt: string | null;
      caption: string | null;
    }> | null;
  };
  links: Array<{
    label?: string;
    url?: string;
    _key: string;
  }> | null;
  embeds: Array<{
    _key: string;
  } & Embed | {
    _key: string;
  } & Spotify> | null;
} | null;

// Source: ../site/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(orderRank) {  _id,  _type,  "isDraft": _id in path("drafts.**") || _originalId in path("drafts.**"),  _createdAt,  name,  "slug": slug.current,  "image": image.asset->url,  archived,  type,  svgcode,  subtitle,  color,  displayType,  embedUrl,  aspectRatio,  url,  content}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "project";
  isDraft: boolean;
  _createdAt: string;
  name: string | null;
  slug: string | null;
  image: string | null;
  archived: boolean | null;
  type: "client" | "personal" | null;
  svgcode: Code | null;
  subtitle: string | null;
  color: Color | null;
  displayType: "background" | "embed" | "popup" | null;
  embedUrl: string | null;
  aspectRatio: {
    desktop?: string;
    mobile?: string;
  } | null;
  url: string | null;
  content: Array<{
    _key: string;
  } & Columns | {
    _key: string;
  } & Embed | {
    _key: string;
  } & Gallery | {
    _key: string;
  } & Skills | {
    _key: string;
  } & Spotify | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      reference?: MusicReference | PageReference | ProjectReference;
      _type: "internalLink";
      _key: string;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | {
    media?: MediaMedia;
    _type: "media";
    _key: string;
  } | {
    asset?: SanityFileAssetReference;
    media?: unknown;
    alt?: string;
    _type: "videoFile";
    _key: string;
  }> | null;
}>;

// Source: ../site/sanity/queries.ts
// Variable: PERSONAL_PROJECTS_QUERY
// Query: *[_type == "project" && type == "personal"] | order(orderRank) {  _id,  _type,  "isDraft": _id in path("drafts.**") || _originalId in path("drafts.**"),  _createdAt,  name,  "slug": slug.current,  "image": image.asset->url,  archived,  type,  svgcode,  subtitle,  color,  displayType,  embedUrl,  aspectRatio,  url,  content}
export type PERSONAL_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "project";
  isDraft: boolean;
  _createdAt: string;
  name: string | null;
  slug: string | null;
  image: string | null;
  archived: boolean | null;
  type: "personal";
  svgcode: Code | null;
  subtitle: string | null;
  color: Color | null;
  displayType: "background" | "embed" | "popup" | null;
  embedUrl: string | null;
  aspectRatio: {
    desktop?: string;
    mobile?: string;
  } | null;
  url: string | null;
  content: Array<{
    _key: string;
  } & Columns | {
    _key: string;
  } & Embed | {
    _key: string;
  } & Gallery | {
    _key: string;
  } & Skills | {
    _key: string;
  } & Spotify | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      reference?: MusicReference | PageReference | ProjectReference;
      _type: "internalLink";
      _key: string;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | {
    media?: MediaMedia;
    _type: "media";
    _key: string;
  } | {
    asset?: SanityFileAssetReference;
    media?: unknown;
    alt?: string;
    _type: "videoFile";
    _key: string;
  }> | null;
}>;

// Source: ../site/sanity/queries.ts
// Variable: CLIENT_PROJECTS_QUERY
// Query: *[_type == "project" && type == "client"] | order(orderRank) {  _id,  _type,  "isDraft": _id in path("drafts.**") || _originalId in path("drafts.**"),  _createdAt,  name,  "slug": slug.current,  "image": image.asset->url,  archived,  type,  svgcode,  subtitle,  color,  displayType,  embedUrl,  aspectRatio,  url,  content}
export type CLIENT_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "project";
  isDraft: boolean;
  _createdAt: string;
  name: string | null;
  slug: string | null;
  image: string | null;
  archived: boolean | null;
  type: "client";
  svgcode: Code | null;
  subtitle: string | null;
  color: Color | null;
  displayType: "background" | "embed" | "popup" | null;
  embedUrl: string | null;
  aspectRatio: {
    desktop?: string;
    mobile?: string;
  } | null;
  url: string | null;
  content: Array<{
    _key: string;
  } & Columns | {
    _key: string;
  } & Embed | {
    _key: string;
  } & Gallery | {
    _key: string;
  } & Skills | {
    _key: string;
  } & Spotify | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      reference?: MusicReference | PageReference | ProjectReference;
      _type: "internalLink";
      _key: string;
    } | {
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | {
    media?: MediaMedia;
    _type: "media";
    _key: string;
  } | {
    asset?: SanityFileAssetReference;
    media?: unknown;
    alt?: string;
    _type: "videoFile";
    _key: string;
  }> | null;
}>;

// Source: ../site/sanity/queries.ts
// Variable: MUSIC_LIST_QUERY
// Query: *[_type == "music"] | order(orderRank) {  _id,  _type,  "isDraft": _id in path("drafts.**") || _originalId in path("drafts.**"),  _createdAt,  "slug": coalesce(slug.current, _id),  bandName,  albumName,  releaseYear,  "albumArt": albumArt.asset->url,  "albumArtAlt": albumArt.alt,  "gallery": {    "columns": coalesce(gallery.columns, 2),    "images": coalesce(gallery.images, gallery)[]{      _key,      asset,      "url": asset->url,      alt,      caption    }  },  links,  embeds}
export type MUSIC_LIST_QUERY_RESULT = Array<{
  _id: string;
  _type: "music";
  isDraft: boolean;
  _createdAt: string;
  slug: string;
  bandName: string | null;
  albumName: string | null;
  releaseYear: number | null;
  albumArt: string | null;
  albumArtAlt: string | null;
  gallery: {
    columns: 0 | 1 | 2 | 3 | 4 | 5 | 6;
    images: Array<{
      _key: string;
      asset: SanityImageAssetReference | null;
      url: string | null;
      alt: string | null;
      caption: string | null;
    }> | null;
  };
  links: Array<{
    label?: string;
    url?: string;
    _key: string;
  }> | null;
  embeds: Array<{
    _key: string;
  } & Embed | {
    _key: string;
  } & Spotify> | null;
}>;

// Source: ../site/sanity/queries.ts
// Variable: MUSIC_BY_SLUG_QUERY
// Query: *[_type == "music" && (slug.current == $slug || _id == $slug)][0] {  _id,  _type,  "isDraft": _id in path("drafts.**") || _originalId in path("drafts.**"),  _createdAt,  "slug": coalesce(slug.current, _id),  bandName,  albumName,  releaseYear,  "albumArt": albumArt.asset->url,  "albumArtAlt": albumArt.alt,  "gallery": {    "columns": coalesce(gallery.columns, 2),    "images": coalesce(gallery.images, gallery)[]{      _key,      asset,      "url": asset->url,      alt,      caption    }  },  links,  embeds}
export type MUSIC_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "music";
  isDraft: boolean;
  _createdAt: string;
  slug: string;
  bandName: string | null;
  albumName: string | null;
  releaseYear: number | null;
  albumArt: string | null;
  albumArtAlt: string | null;
  gallery: {
    columns: 0 | 1 | 2 | 3 | 4 | 5 | 6;
    images: Array<{
      _key: string;
      asset: SanityImageAssetReference | null;
      url: string | null;
      alt: string | null;
      caption: string | null;
    }> | null;
  };
  links: Array<{
    label?: string;
    url?: string;
    _key: string;
  }> | null;
  embeds: Array<{
    _key: string;
  } & Embed | {
    _key: string;
  } & Spotify> | null;
} | null;

// Source: ../site/sanity/queries.ts
// Variable: PROJECT_NEXT_QUERY
// Query: *[_type == "project" && orderRank > $orderRank] | order(orderRank) [0] {  _id,  "isDraft": _id in path("drafts.**") || _originalId in path("drafts.**"),  name,  "slug": slug.current,  "image": image.asset->url}
export type PROJECT_NEXT_QUERY_RESULT = {
  _id: string;
  isDraft: boolean;
  name: string | null;
  slug: string | null;
  image: string | null;
} | null;

// Source: ../site/sanity/queries.ts
// Variable: PROJECT_PREV_QUERY
// Query: *[_type == "project" && orderRank < $orderRank] | order(orderRank desc) [0] {  _id,  "isDraft": _id in path("drafts.**") || _originalId in path("drafts.**"),  name,  "slug": slug.current,  "image": image.asset->url}
export type PROJECT_PREV_QUERY_RESULT = {
  _id: string;
  isDraft: boolean;
  name: string | null;
  slug: string | null;
  image: string | null;
} | null;

// Source: ../site/sanity/queries.ts
// Variable: PAGES_QUERY
// Query: *[_type == "page"]{  _id,  _createdAt,  title,  "slug": slug.current}
export type PAGES_QUERY_RESULT = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
}>;

// Source: ../site/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{  _id,  _createdAt,  title,  subtitle,  "slug": slug.current,  content[]{    ...,    _type == "image" => {      "imageUrl": asset->url,      "alt": alt    }  }}
export type PAGE_QUERY_RESULT = {
  _id: string;
  _createdAt: string;
  title: string | null;
  subtitle: string | null;
  slug: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "columns";
    columns?: Array<{
      content?: Array<{
        _key: string;
      } & Columns | {
        _key: string;
      } & Embed | {
        _key: string;
      } & Gallery | {
        _key: string;
      } & Skills | {
        _key: string;
      } & Spotify | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      } | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      } | {
        media?: MediaMedia;
        _type: "media";
        _key: string;
      }>;
      _type: "column";
      _key: string;
    }>;
    valign?: "bottom" | "center" | "top";
  } | {
    _key: string;
    _type: "embed";
    url?: string;
    title?: string;
    width?: "content" | "full";
    ratio?: Ratio;
    aspectRatio?: string;
  } | {
    _key: string;
    _type: "gallery";
    columns?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
    images?: Array<{
      _key: string;
    } & GalleryImage>;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
    _key: string;
    imageUrl: string | null;
  } | {
    media?: MediaMedia;
    _type: "media";
    _key: string;
  } | {
    _key: string;
    _type: "skills";
    placeholder?: string;
  } | {
    _key: string;
    _type: "spotify";
    url?: string;
    size?: "compact" | "default";
    theme?: "dark" | "light";
    title?: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"project\" && slug.current == $slug][0]{\n  _id,\n  _type,\n  \"isDraft\": _id in path(\"drafts.**\") || _originalId in path(\"drafts.**\"),\n  _createdAt,\n  name,\n  \"slug\": slug.current,\n  \"image\": image.asset->url,\n  subtitle,\n  svgcode,\n  url,\n  archived,\n  siteMini,\n  orderRank,\n  \"leadIn\": leadIn[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      \"slug\": @.reference->slug.current,\n      \"refType\": @.reference->_type\n    },\n    _type == \"link\" => {\n      ...,\n    }\n  }\n},\n  \"content\": content[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      \"slug\": @.reference->slug.current,\n      \"refType\": @.reference->_type\n    },\n    _type == \"link\" => {\n      ...,\n    }\n  }\n}\n}": PROJECT_QUERY_RESULT;
    "*[_type == \"music\" && (slug.current == $slug || _id == $slug)][0]{\n  _id,\n  _type,\n  \"isDraft\": _id in path(\"drafts.**\") || _originalId in path(\"drafts.**\"),\n  _createdAt,\n  \"slug\": coalesce(slug.current, _id),\n  bandName,\n  albumName,\n  releaseYear,\n  \"albumArt\": albumArt.asset->url,\n  \"albumArtAlt\": albumArt.alt,\n  \"gallery\": {\n    \"columns\": coalesce(gallery.columns, 2),\n    \"images\": coalesce(gallery.images, gallery)[]{\n      _key,\n      asset,\n      \"url\": asset->url,\n      alt,\n      caption\n    }\n  },\n  links,\n  embeds\n}": MUSIC_QUERY_RESULT;
    "*[_type == \"project\"] | order(orderRank) {\n  _id,\n  _type,\n  \"isDraft\": _id in path(\"drafts.**\") || _originalId in path(\"drafts.**\"),\n  _createdAt,\n  name,\n  \"slug\": slug.current,\n  \"image\": image.asset->url,\n  archived,\n  type,\n  svgcode,\n  subtitle,\n  color,\n  displayType,\n  embedUrl,\n  aspectRatio,\n  url,\n  content\n}": PROJECTS_QUERY_RESULT;
    "*[_type == \"project\" && type == \"personal\"] | order(orderRank) {\n  _id,\n  _type,\n  \"isDraft\": _id in path(\"drafts.**\") || _originalId in path(\"drafts.**\"),\n  _createdAt,\n  name,\n  \"slug\": slug.current,\n  \"image\": image.asset->url,\n  archived,\n  type,\n  svgcode,\n  subtitle,\n  color,\n  displayType,\n  embedUrl,\n  aspectRatio,\n  url,\n  content\n}": PERSONAL_PROJECTS_QUERY_RESULT;
    "*[_type == \"project\" && type == \"client\"] | order(orderRank) {\n  _id,\n  _type,\n  \"isDraft\": _id in path(\"drafts.**\") || _originalId in path(\"drafts.**\"),\n  _createdAt,\n  name,\n  \"slug\": slug.current,\n  \"image\": image.asset->url,\n  archived,\n  type,\n  svgcode,\n  subtitle,\n  color,\n  displayType,\n  embedUrl,\n  aspectRatio,\n  url,\n  content\n}": CLIENT_PROJECTS_QUERY_RESULT;
    "*[_type == \"music\"] | order(orderRank) {\n  _id,\n  _type,\n  \"isDraft\": _id in path(\"drafts.**\") || _originalId in path(\"drafts.**\"),\n  _createdAt,\n  \"slug\": coalesce(slug.current, _id),\n  bandName,\n  albumName,\n  releaseYear,\n  \"albumArt\": albumArt.asset->url,\n  \"albumArtAlt\": albumArt.alt,\n  \"gallery\": {\n    \"columns\": coalesce(gallery.columns, 2),\n    \"images\": coalesce(gallery.images, gallery)[]{\n      _key,\n      asset,\n      \"url\": asset->url,\n      alt,\n      caption\n    }\n  },\n  links,\n  embeds\n}": MUSIC_LIST_QUERY_RESULT;
    "*[_type == \"music\" && (slug.current == $slug || _id == $slug)][0] {\n  _id,\n  _type,\n  \"isDraft\": _id in path(\"drafts.**\") || _originalId in path(\"drafts.**\"),\n  _createdAt,\n  \"slug\": coalesce(slug.current, _id),\n  bandName,\n  albumName,\n  releaseYear,\n  \"albumArt\": albumArt.asset->url,\n  \"albumArtAlt\": albumArt.alt,\n  \"gallery\": {\n    \"columns\": coalesce(gallery.columns, 2),\n    \"images\": coalesce(gallery.images, gallery)[]{\n      _key,\n      asset,\n      \"url\": asset->url,\n      alt,\n      caption\n    }\n  },\n  links,\n  embeds\n}": MUSIC_BY_SLUG_QUERY_RESULT;
    "*[_type == \"project\" && orderRank > $orderRank] | order(orderRank) [0] {\n  _id,\n  \"isDraft\": _id in path(\"drafts.**\") || _originalId in path(\"drafts.**\"),\n  name,\n  \"slug\": slug.current,\n  \"image\": image.asset->url\n}": PROJECT_NEXT_QUERY_RESULT;
    "*[_type == \"project\" && orderRank < $orderRank] | order(orderRank desc) [0] {\n  _id,\n  \"isDraft\": _id in path(\"drafts.**\") || _originalId in path(\"drafts.**\"),\n  name,\n  \"slug\": slug.current,\n  \"image\": image.asset->url\n}": PROJECT_PREV_QUERY_RESULT;
    "*[_type == \"page\"]{\n  _id,\n  _createdAt,\n  title,\n  \"slug\": slug.current\n}": PAGES_QUERY_RESULT;
    "*[_type == \"page\" && slug.current == $slug][0]{\n  _id,\n  _createdAt,\n  title,\n  subtitle,\n  \"slug\": slug.current,\n  content[]{\n    ...,\n    _type == \"image\" => {\n      \"imageUrl\": asset->url,\n      \"alt\": alt\n    }\n  }\n}": PAGE_QUERY_RESULT;
  }
}

